version: '3.8'

services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    restart: always

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    restart: always   